on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: lighthouse-ci/lighthouse-ci-action@v1
        with:
          config-file: '.lighthouserc.js'

      - name: Fail if any conventional score is below threshold
        if: ${{ steps.lighthouse-ci.outputs.performance < steps.lighthouse-ci.outputs.passingConventionalScores.performance || steps.lighthouse-ci.outputs.accessibility < steps.lighthouse-ci.outputs.passingConventionalScores.accessibility || steps.lighthouse-ci.outputs.bestPractices < steps.lighthouse-ci.outputs.passingConventionalScores.bestPractices || steps.lighthouse-ci.outputs.seo < steps.lighthouse-ci.outputs.passingConventionalScores.seo }}
        run: exit 1
