name: CI
on: [push]

env:
  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL1 }}
jobs:
  lighthouseFoo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir -p ${{ github.workspace }}/tmp/artifacts
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      id: lighthouseCheck
      with:
        outputDirectory: ${{ github.workspace }}/tmp/artifacts
        urls: 'https://groww.in/'
        slackWebhookUrl: ${{secrets.SLACK_WEBHOOK_URL1}}
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: lhciR
        path: ${{ github.workspace }}/tmp/artifacts
  
  slack_download_job:
    runs-on: ubuntu-latest
    needs: lighthouseFoo
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        id: download
        with:
          name: lhciR
          
      - name: Display structure of downloaded files
        run: ls -R
      
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}} 
      - name: 'Listing'
        run: pwd
      - name: 'Listing1'
        run: ls -l
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": ${{steps.download.outputs}} 
            }
     
      
      
          
  # slack_upload_job:
  #   needs: lighthouseFoo
  #   runs-on: ubuntu-latest
  #   name: upload
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v1
  #     - name: Slack new
  #       uses: MeilCli/slack-upload-file@v3
  #       with:
  #         slack_token: {{ secrets.SLACK_TOKEN }}
  #         channel_id: {{ secrets.SLACK_WEBHOOK_URL1 }}
  #         content: 'file content'
  #         file_type: 'json'
  #         file_name: 'results.json'
  #         initial_comment: 'post by slack-upload-file'
          
  