name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install && npm install -g @lhci/cli@0.8.x
      - run: npm run build
      - run: lhci collect
      - run: lhci upload
      - run: lhci autorun
        env:
            LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
            SLACK_WEBHOOk_URL: ${{ secrets.SLACK_WEBHOOk_URL }}
      - name: Slack Notification
      uses: act10ns/slack@v1
      with: 
        status: ${{ job.status }}
        channel: '#meetups'
        message: Build {{ env.GITHUB_REF_NAME }} branch Successfully
      if: always()