name: CI
on: [push]

env:
  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  # SLACK_WEBHOOK_URL: {{ secrets.SLACK_WEBHOOK_URL1 }}
jobs:
  lighthouseFoo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir -p ${{ github.workspace }}/tmp/artifacts
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      id: lighthouseCheck
      with:
        outputDirectory: ${{ github.workspace }}/tmp/artifacts
        urls: 'https://groww.in/,https://groww.in/download-forms,https://groww.in/blog,https://groww.in/blog/best-diwali-stocks-to-invest,https://groww.in/blog/best-fixed-deposit-in-india,https://groww.in/blog/best-gold-stocks-in-india,https://groww.in/p,https://groww.in/p/income-funds'
        slackWebhookUrl: ${{secrets.SLACK_WEBHOOK_URL}}
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: ${{ github.workspace }}/tmp/artifacts

    - name: Verify Lighthouse Check results
      uses: foo-software/lighthouse-check-status-action@master
      with:
        lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
        minAccessibilityScore: "90"
        minBestPracticesScore: "50"
        minPerformanceScore: "50"
        minProgressiveWebAppScore: "50"
        minSeoScore: "50"
  # lighthouseci:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 16
  #     - run: npm install && npm install -g @lhci/cli@0.8.x
  #     - run: lhci collect
  #     - run: lhci upload
  #     - run: lhci autorun

  #     - name: Slack Notification
  #       uses: act10ns/slack@v2.0.0
  #       with:
  #         status: ${{ job.status }}
  #         steps: ${{ toJson(steps) }}
  #         channel: "#temp-turbo"
  #         message: Test Ran {{ env.GITHUB_REF_NAME }}



  # send-slack-notification-bgv:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Send Slack Notification

  #       run: |
  #         curl -X POST -H 'Content-type: application/json' --data '{
  #           "text": "dummy check LHCI"
  #         }' $SLACK_WEBHOOK_URL
