name: CI
on: [push]

env:
  LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  # SLACK_WEBHOOK_URL: {{ secrets.SLACK_WEBHOOK_URL1 }}
jobs:
  lighthouseFoo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir -p ${{ github.workspace }}/tmp/artifacts
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      id: lighthouseCheck
      with:
        outputDirectory: ${{ github.workspace }}/tmp/artifacts
        urls: 'https://groww.in/'
        slackWebhookUrl: ${{secrets.SLACK_WEBHOOK_URL1}}
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: lhciR
        path: ${{ github.workspace }}/tmp/artifacts
        
          
  slack_upload_job:
    needs: lighthouseFoo
    runs-on: ubuntu-latest
    name: upload
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Upload to slack
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{secrets.SLACK_WEBHOOK_URL1}}
          path: ${{ github.workspace }}/tmp/artifacts/
          
  slack_download_job:
    runs-on: ubuntu-latest
    needs: lighthouseFoo
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        id: download
        with:
          name: lhciR
          
      - name: Display structure of downloaded files
        run: ls -R
      
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}} 
      - name: 'Listing'
        run: ls